### ISSUE TITLE
React 14-rc

### ISSUE THREAD

**Issue by tomatau** [vigetlabs/react-ink#16]
Great Component really like it.

On npm@3, getting peerDependency warning when used with React-14

Currently you have:
```
"react": ">= 0.12 < 0.14"
```
But this component is working for me on rc14, can this peerDependency be changed?

**Comment by nhunzaker** [comment]
Yep! It probably means it's about time. I'll take a look

**Comment by tomatau** [comment]
Cool thanks.  The warning got the better of my OCD and I've made a fork to use this from a npm github dependency (tracking dist).

Here's the fork and branch. https://github.com/tomatau/react-ink/tree/react-0.14

I would pr but I think it's a breaking change to anyone on 0.13.

**Comment by nhunzaker** [comment]
Cool. This will be a breaking release either way. @tomatau PR me and we'll make a major release.

**Comment by tomatau** [comment]
OK :)

https://github.com/vigetlabs/react-ink/pull/17/files

**Comment by nhunzaker** [comment]
:heart_eyes: I'm going to look at this later today. I'd also like to drop webpack as the distribution build system and just use it for the example app.

**Comment by nhunzaker** [comment]
(And use pure babel instead for dist)
