### ISSUE TITLE
Failed to parse SourceMap: http://localhost:3000/js/ink.js.map

### ISSUE THREAD

**Issue by nparsons08** [vigetlabs/react-ink#21]
Looks like Chrome is complaining about a missing map file. Any ideas on how to resolve this?

**Comment by nparsons08** [comment]
Really? It takes this long to get back to a question?

**Comment by nhunzaker** [comment]
Hey Nick. You're absolutely right, it's been a busy month, but I should have responded earlier.

I've released a patch version that switches the source map strategy to inline.

https://github.com/vigetlabs/react-ink/commit/9a91af6fb2c8034b357f26278d62dceeee66d710

This is release `5.1.1`. Give it a shot. I'll be able to touch base later today if you still have issues.
