### ISSUE TITLE
Invalid prop 'onTouchLeave' on <canvas> tag.

### ISSUE THREAD

**Issue by lukaswelinder** [vigetlabs/react-ink#26]
'Warning: Unknown prop `onTouchLeave` on <canvas> tag.'

**Comment by nhunzaker** [comment]
Yikes! Let's patch this up...

**Comment by nhunzaker** [comment]
Okay, looks like TouchLeave was a proposal that was never implemented. Great. I'll get rid of it.

**Comment by nhunzaker** [comment]
@lukaswelinder Shipped as v6.0.0. Please let me know if you hit any additional trouble.

**Comment by lukaswelinder** [comment]
Awesome, thanks for the prompt follow up on that @nhunzaker.
