### ISSUE TITLE
Doesn't seem to be working

### ISSUE THREAD

**Issue by mnemanja** [vigetlabs/react-ink#29]
Latest chrome, react v15.4.2.

The canvas element gets applied, but when I click it nothing happens.
The Readme file is so slim and concise that I thought it should be easy but that doesn't seem to be the case.

**Comment by nhunzaker** [comment]
Hmm. I just upgraded the example to 15.4.2, no issues. Would you be willing to provide me some sample code for how you are using react-ink?

**Comment by mnemanja** [comment]
@nhunzaker ,
Unfortunately I currently lack time to devote to this issue. As far as I'm concerned this issue can stay open or closed for others to interact with.

Cheers,
Nemanja

**Comment by nhunzaker** [comment]
Okay. I'll go ahead and close this then, if it crops up, we'll take a look!
