### ISSUE TITLE
Deprecation warning in React v15.5.x

### ISSUE THREAD

**Issue by jaredlunde** [vigetlabs/react-ink#32]
React v16 will drop React.createClass

```Warning: Ink: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.```

**Comment by nhunzaker** [comment]
Ah man. Yep. I'm just a little behind here.

**Comment by nhunzaker** [comment]
Done:
https://github.com/vigetlabs/react-ink/releases/tag/v6.2.0

**Comment by jaredlunde** [comment]
Excellent, thank you very much.
