### ISSUE TITLE
Feature request: configurable color

### ISSUE THREAD

**Issue by icd2k3** [vigetlabs/react-ink#35]
This package is great! I recently decided to avoid bootstrap libraries like react-toolbox and material-ui in favor of my own components and this lets me add the ripple effect to them very easily.

Sometimes the text color of the element doesn't look great as the color of the ripple. I'd love an optional prop to override the default color - noticed a PR was open here https://github.com/vigetlabs/react-ink/pull/19 but it's pretty old...

**Comment by SleepWalker** [comment]
try to set color on canvas, like in the demo:

https://github.com/vigetlabs/react-ink/blob/master/example/index.html#L13-L15

**Comment by nhunzaker** [comment]
Hey, yep! The canvas uses it's current color, so the color is configurable using CSS.

If I remember correctly, you can also use this to transition the color for error/disabled/etc states.
