### ISSUE TITLE
Update legacy string refs

### ISSUE THREAD

**Issue by greypants** [vigetlabs/react-ink#38]
[String refs are deprecated!](https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs) A coworker noticed string refs here that should probably be updated soon: https://github.com/vigetlabs/react-ink/blob/master/src/index.js#L135

**Comment by nhunzaker** [comment]
Hey Dan!

Sorry, I just got back from over-seas and I'm catching up on some stuff. This should be pretty quick. I'll send out a PR for it Tuesday.

**Comment by nhunzaker** [comment]
Deployed in 6.3.0
