### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by cgarvis** [vigetlabs/react-ink#4]
I had a problem with the lib when using a button.  I had to dig into the example to figure it out.  I had to add `position: 'relative'` to my button style.

```
<button style={{ position: 'relative' }}>
  Button
  <Ink />
</button>
```

**Comment by nhunzaker** [comment]
Sorry for the delay. Yes! Actually I'm in the middle of refactoring `react-ink` to better match the [`RippleDrawable`](https://developer.android.com/reference/android/graphics/drawable/RippleDrawable.html) Android class. This gives us an "ideal" spec to follow. Substantial documentation will be a part of this.

**Comment by nhunzaker** [comment]
I'm going to close this one out, we've added a note in the usage instructions on positioning.
