### ISSUE TITLE
Not working in Firefox 62.0.2 (64-bit) and Internet Explorer 11

### ISSUE THREAD

**Issue by nikbelikov** [vigetlabs/react-ink#44]
But if I replace button with div it works, but it's not valid semantic idea and all buttons lose all standard buttons behavior in form tag.

**Comment by geocool** [comment]
I can confirm that it's not working on firefox.

**Comment by geocool** [comment]
Just tested Firefox 66 and it's working now.

**Comment by nhunzaker** [comment]
Awesome, good deal :+1:
