### ISSUE TITLE
Entry point for latest release v6.5.0 doesn't exist

### ISSUE THREAD

**Issue by matiasibar** [vigetlabs/react-ink#56]
package.json file says  `"main": "dist/ink.js"`  but that file doesn't exist on the published package.
Instead I found a "dist" file with the needed bundle.

**Comment by cwmanning** [comment]
Thanks, @matiasibar. Looking into it.

**Comment by cwmanning** [comment]
Should be working now - released as `6.5.1`. Let me know if not!

**Comment by matiasibar** [comment]
Great! It works.
Thanks!
