### ISSUE TITLE
Also propagate on right-click?

### ISSUE THREAD

**Issue by vlad-solomon** [vigetlabs/react-ink#73]
Is there any way to make this also work when right-clicking?
So adding an event listener for "contextmenu" or detecting the button onmousedown? This seems it only triggers on left clicking.

**Comment by cwmanning** [comment]
@vlad-solomon good question! I am not the author of this library, but the event handler appears to check specifically for a left mouse click. See https://github.com/vigetlabs/react-ink/blob/master/src/index.js#L171 for an example. 

Left click is not a typical use case for this library, but if you're up for creating a fork, removing the `MOUSE_LEFT` check looks like a small level of effort.

**Comment by vlad-solomon** [comment]
Oh wow, thank you. I skimmed through that file but the ```button === MOUSE_LEFT && !ctrlKey``` check seems to have eluded me.
